# Generated by Django 3.2.7 on 2021-10-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('monto', models.CharField(max_length=10)),
                ('tipo_pago', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_carta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ca_nombre', models.CharField(max_length=35)),
                ('ca_desc', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom_ciudad', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('c_rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad', models.BigIntegerField()),
                ('estado_orden', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('e_rut', models.BigIntegerField(primary_key=True, serialize=False)),
                ('e_dv', models.CharField(max_length=1)),
                ('prim_nom', models.CharField(max_length=30)),
                ('seg_nom', models.CharField(blank=True, max_length=25, null=True)),
                ('prim_apell', models.CharField(max_length=30)),
                ('sec_apell', models.CharField(max_length=25)),
                ('genero', models.CharField(max_length=25)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fec_nac', models.CharField(max_length=30)),
                ('salario', models.BigIntegerField()),
                ('correo', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaDesp',
            fields=[
                ('id_envio', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('monto_neto', models.CharField(max_length=20)),
                ('iva', models.BigIntegerField()),
                ('total', models.CharField(max_length=12)),
                ('fec_envio', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'guia_desp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom_ingrediente', models.CharField(max_length=40)),
                ('desc_ingrediente', models.CharField(max_length=60)),
                ('stock', models.BigIntegerField()),
                ('unidad_de_medida', models.CharField(max_length=20)),
                ('fec_caduc', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('capacidad', models.BigIntegerField()),
                ('estareservada', models.FloatField()),
                ('tieneorden', models.FloatField()),
            ],
            options={
                'db_table': 'mesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=16)),
                ('hora', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_social', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('giro', models.CharField(blank=True, max_length=30, null=True)),
                ('p_nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=80)),
                ('p_correo', models.CharField(max_length=80)),
                ('p_telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=60)),
                ('razon_social', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nom_receta', models.CharField(max_length=20)),
                ('desc_receta', models.CharField(max_length=80)),
                ('porcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fec_reserva_hecha', models.DateField()),
                ('fec_reserva', models.DateField()),
                ('origen_reserva', models.CharField(max_length=15)),
                ('estado_reserva', models.CharField(max_length=10)),
                ('cant_personas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolEmpleado',
            fields=[
                ('id_rol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rol_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rol_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id_suministro', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tamannio', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=40)),
                ('s_desc', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'suministro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleGuia',
            fields=[
                ('comentario', models.CharField(max_length=400)),
                ('guia_desp_id_envio', models.OneToOneField(db_column='guia_desp_id_envio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Reserva.guiadesp')),
                ('gd_desc', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad', models.CharField(max_length=20)),
                ('u_medida', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'detalle_guia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('instruccion', models.CharField(max_length=400)),
                ('ingrediente_id_ingrediente', models.OneToOneField(db_column='ingrediente_id_ingrediente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Reserva.ingrediente')),
            ],
            options={
                'db_table': 'detalle_receta',
                'managed': False,
            },
        ),
    ]
