# Generated by Django 3.2.7 on 2021-10-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_carta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ca_nombre', models.CharField(max_length=35)),
                ('ca_desc', models.CharField(max_length=80)),
                ('precio', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'carta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiaDesp',
            fields=[
                ('id_envio', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('monto_neto', models.CharField(max_length=20)),
                ('iva', models.BigIntegerField()),
                ('total', models.CharField(max_length=12)),
                ('fec_envio', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'guia_desp',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdministradorUsuario',
        ),
        migrations.DeleteModel(
            name='DetalleReserva',
        ),
        migrations.DeleteModel(
            name='GuiaDespacho',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.CreateModel(
            name='DetalleGuia',
            fields=[
                ('comentario', models.CharField(max_length=400)),
                ('guia_desp_id_envio', models.OneToOneField(db_column='guia_desp_id_envio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Usuarios.guiadesp')),
                ('gd_desc', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad', models.CharField(max_length=20)),
                ('u_medida', models.CharField(max_length=30)),
                ('precio', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'detalle_guia',
                'managed': False,
            },
        ),
    ]
