# Generated by Django 3.2.7 on 2021-11-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bodega', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
